### ISSUE TITLE
Plugin no longer working as expected after recent changes

### ISSUE THREAD

**Issue by cjk** [marlonrichert/zsh-hist#23]
## Describe the bug
Before commit 6b0e5e65bc477357b66df35cd93a1752bae85e03 this plugin was working as expected for me:
`^q` pushed a command to history and `^g` retrieved it from history - perfect! :smile: 

After the commit from above on Feb. 07 2023, this functionality broke. Now, when I press `^q` the current command is added to the buffer-stack instead and automatically poped when I press `enter` :disappointed: 

## Steps To Reproduce
```zsh
zinit light-mode for marlonrichert/zsh-hist
```

The above works as expected *before Feb. 07* and stops working *after* Feb. 07

## Expected behavior
Should continue to work as described, even after the changes introduced in February

## Environment:
 - OS: Arch Linux
 - Terminal: Kitty 
 - Zsh version: zsh 5.9 (x86_64-pc-linux-gnu)
 - Repo version: latest

## Additional context
I know you frown upon using `zinit`, however it worked flawlessly before, so perhaps it's not even `zinit`'s fault?

**Comment by marlonrichert** [comment]
I'm unable to reproduce that. Here's the test environment I used:
```sh
cd $(mktemp -d)
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='%^'; setopt transientrprompt interactivecomments
source /path/to/zsh-hist/zsh-hist.plugin.zsh
EOF
HOME=$PWD ZDOTDIR=$PWD zsh -d
```
Please try it in this environment and if the bug doesn't occur there, then the problem is definitely with Zinit. If you can find a way in which I can reproduce this that doesn't involve Zinit, then I'll reopen the issue.

There is no longer a keybinding for retrieving saved items from history, because there's plenty of keybindings for that already.

I did find some other bugs in my testing and pushed in a fix for those.

**Comment by cjk** [comment]
Hey @marlonrichert , thanks for giving it a try, I can understand your notion here.
I'd also blame it on zinit, however simply reverting back to the commit prior the push-changes instantly fixes the problem for me.

Nevertheless, I'll try to analyze deeper once I get a chance and try without zinit.

**Comment by marlonrichert** [comment]
What output do you get from `bindkey '^Q'`?

**Comment by cjk** [comment]
> What output do you get from `bindkey '^Q'`?

```
❯ bindkey '^Q'
"^Q" push-line-or-edit
```
